/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class operacoes_matrizes_multiplicacao_Multiplicacao_Matrizes */

#ifndef _Included_operacoes_matrizes_multiplicacao_Multiplicacao_Matrizes
#define _Included_operacoes_matrizes_multiplicacao_Multiplicacao_Matrizes
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     operacoes_matrizes_multiplicacao_Multiplicacao_Matrizes
 * Method:    multiplicarMatrizes
 * Signature: ([F[F[FI)V
 */
JNIEXPORT void JNICALL Java_operacoes_1matrizes_multiplicacao_Multiplicacao_1Matrizes_multiplicarMatrizes
  (JNIEnv *, jobject, jfloatArray, jfloatArray, jfloatArray, jint);

#ifdef __cplusplus
}
#endif
#endif
